In [1]:
class PriorityQueue:
    def __init__(self):
        self.pq = []    # array of node names
        self.qp = {}    # inverse of pq, qp[pq[i]] = pq[qp[i]] = i
        self.keys = {}  # array of element keys/priorities
        self.size = 0   # current size of the priority queue

    def is_empty(self):
        return self.size == 0

    def extract_min(self):
        if self.size == 0:
            raise Exception('Heap is empty!')
        min_name = self.pq[0]
        self.swap(0, self.size - 1)
        self.pq.pop()
        del self.qp[min_name]
        del self.keys[min_name]
        self.size -= 1
        self.sink(0)
        return min_name

    def insert(self, name, key):
        self.size += 1
        self.qp[name] = self.size - 1
        self.keys[name] = key
        self.pq.append(name)
        self.swim(self.size - 1)

    def decrease_key(self, name, new_key):
        if name in self.qp:
            self.keys[name] = new_key
            self.sink(self.qp[name])
            self.swim(self.qp[name])
        else:
            raise Exception('No such element exists!')

    def swap(self, i, j):
        self.pq[i], self.pq[j] = self.pq[j], self.pq[i]
        self.qp[self.pq[i]] = i
        self.qp[self.pq[j]] = j

    def swim(self, k):
        while k > 0 and self.keys[self.pq[k]] < self.keys[self.pq[(k - 1) // 2]]:
            self.swap(k, (k - 1) // 2)
            k = (k - 1) // 2

    def sink(self, k):
        while 2 * k + 1 < self.size:
            j = 2 * k + 1
            if j < self.size - 1 and self.keys[self.pq[j]] > self.keys[self.pq[j + 1]]:
                j += 1
            if self.keys[self.pq[k]] <= self.keys[self.pq[j]]:
                break
            self.swap(k, j)
            k = j
    def contains(self, name):
            return name in self.qp


In [2]:
import scipy.io #import mathlab tabs
graph1 = scipy.io.loadmat('/Users/Utente/Desktop/PhD class/CE290I/Assignment2/Assignment 2/graphs/graph1.mat')
graph2 = scipy.io.loadmat('/Users/Utente/Desktop/PhD class/CE290I/Assignment2/Assignment 2/graphs/graph2.mat')
graph3 = scipy.io.loadmat('/Users/Utente/Desktop/PhD class/CE290I/Assignment2/Assignment 2/graphs/graph3.mat')
graph4 = scipy.io.loadmat('/Users/Utente/Desktop/PhD class/CE290I/Assignment2/Assignment 2/graphs/graph4.mat')
graph5 = scipy.io.loadmat('/Users/Utente/Desktop/PhD class/CE290I/Assignment2/Assignment 2/graphs/graph5.mat')
graph6 = scipy.io.loadmat('/Users/Utente/Desktop/PhD class/CE290I/Assignment2/Assignment 2/graphs/graph6.mat')

In [3]:
import numpy as np


# Extract the 'graph1' variable from the loaded data
graph_data1 = graph1['graph1']
graph_data2 = graph2['graph2']
graph_data3 = graph3['graph3']
graph_data4 = graph4['graph4']
graph_data5 = graph5['graph5']
graph_data6 = graph6['graph6']

# Convert the extracted data into a NumPy array
array1 = np.array(graph_data1, dtype=int)
array2 = np.array(graph_data2, dtype=int)
array3 = np.array(graph_data3, dtype=int)
array4 = np.array(graph_data4, dtype=int)
array5 = np.array(graph_data5, dtype=int)
array6 = np.array(graph_data6, dtype=int)

# Get the number of nodes in the graph
num_nodes1 = len(array1)
num_nodes2 = len(array2)
num_nodes3 = len(array3)
num_nodes4 = len(array4)
num_nodes5 = len(array5)
num_nodes6 = len(array6)

# Initialize an empty adjacency matrix
adjacency_matrix1 = np.zeros((num_nodes1, num_nodes1), dtype=int)
adjacency_matrix2 = np.zeros((num_nodes2, num_nodes2), dtype=int)
adjacency_matrix3 = np.zeros((num_nodes3, num_nodes3), dtype=int)
adjacency_matrix4 = np.zeros((num_nodes4, num_nodes4), dtype=int)
adjacency_matrix5 = np.zeros((num_nodes5, num_nodes5), dtype=int)
adjacency_matrix6 = np.zeros((num_nodes6, num_nodes6), dtype=int)

# Fill in the adjacency matrix based on the array1
for i in range(num_nodes1):
    for j in range(num_nodes1):
        if array1[i, j] != 0:
            adjacency_matrix1[i, j] = array1[i, j]

# Fill in the adjacency matrix based on the array2
for i in range(num_nodes2):
    for j in range(num_nodes2):
        if array2[i, j] != 0:
            adjacency_matrix2[i, j] = array2[i, j]
            

# Fill in the adjacency matrix based on the array3
for i in range(num_nodes3):
    for j in range(num_nodes3):
        if array3[i, j] != 0:
            adjacency_matrix3[i, j] = array3[i, j]
            
            

# Fill in the adjacency matrix based on the array4
for i in range(num_nodes4):
    for j in range(num_nodes4):
        if array4[i, j] != 0:
            adjacency_matrix4[i, j] = array4[i, j]
            

# Fill in the adjacency matrix based on the array5
for i in range(num_nodes5):
    for j in range(num_nodes5):
        if array5[i, j] != 0:
            adjacency_matrix5[i, j] = array5[i, j]
            

# Fill in the adjacency matrix based on the array6
for i in range(num_nodes6):
    for j in range(num_nodes6):
        if array6[i, j] != 0:
            adjacency_matrix6[i, j] = array6[i, j]

            
                        
            
            
# Print the adjacency matrix
print(adjacency_matrix1)
print(adjacency_matrix2)
print(adjacency_matrix3)
print(adjacency_matrix4)
print(adjacency_matrix5)
print(adjacency_matrix6)


[[ 0  8  0 17  0  0  0]
 [ 7  0 17  0  0  0  0]
 [ 0 16  0 18 11  0  0]
 [13 13  0  0  0 20  9]
 [ 0  0  2  0  0 18  0]
 [ 0  0 13  0  8  0 20]
 [ 0  0  0  5  0 14  0]]
[[ 0  5  0  0  0  0]
 [ 0  0  2  0  0  0]
 [ 1  0  0  0  0  0]
 [ 9  0  6  0  3  0]
 [ 0  9  0  0  0  5]
 [ 0  0  0 11  0  0]]
[[0 0 4 0]
 [2 0 6 2]
 [0 2 0 6]
 [0 0 0 0]]
[[ 0  0 42 45 47]
 [ 0  0  0 77  6]
 [11  3  0  0  0]
 [ 0 76 22  0  0]
 [80  0 87  0  0]]
[[   0  691  941    0 1196  817   12   51  940  896]
 [1107    0  961  405  724  901  274  166    0  426]
 [   0   22    0  331 1187  615 1128  872    0  926]
 [   0  460  741    0  821  701  966  293    0    0]
 [1093    0  963  976    0  641  416  426  921 1063]
 [1135  740  542  643  493    0  355    0 1184  100]
 [1182  634  795   36  262 1186    0  497  129 1064]
 [  52    0  546    0 1166  151  299    0 1012  219]
 [1128    0  262    0  371  105  494  812    0  663]
 [1079    0  864    0   81  637  833  752  701    0]]
[[   0    0  390    0  833 1051 1373 

In [4]:
import numpy as np

def dijkstra(adj_matrix1, origin): #his function implements Dijkstra's algorithm to find the shortest distances and previous nodes for each node in a graph
    #The adjacency matrix of the graph, representing edge weights (distances) between nodes.
    #The adjacency matrix of the graph, representing edge weights (distances) between nodes.
    num_nodes1 = len(adj_matrix1)
    #Initialize arrays dist and prev to store the distances from the origin node to all other nodes and the previous node on the shortest path, respectively
    dist = [float('inf')] * num_nodes1  
    prev = [None] * num_nodes1
    #Initialize dist with infinity for all nodes except the origin, which is set to 0.
    dist[origin] = 0

    pq = PriorityQueue() #Create a priority queue pq to manage nodes and their distances.
    pq.insert(origin, 0)#Insert the origin node with a distance of 0 into the priority queue.

    while not pq.is_empty(): #The function enters a while loop to process nodes while the priority queue is not empty
        u = pq.extract_min()#Extract the node u with the smallest distance from the priority queue
        for v in range(num_nodes1): #Iterate through all nodes v in the graph
            if adj_matrix1[u][v] > 0:
                alt = dist[u] + adj_matrix1[u][v]#For each adjacent node v to u calculate an alternative distance alt from the origin to v through u.
                if alt < dist[v]: #If alt is smaller than the current distance dist[v], update dist[v], set prev[v] to u, and adjust the priority queue accordingly by either decreasing the key or inserting a new element.
                    dist[v] = alt
                    prev[v] = u
                    if pq.contains(v):
                        pq.decrease_key(v, alt)
                    else:
                        pq.insert(v, alt)

    return dist, prev #After the while loop, the function returns the arrays dist and prev, which contain the shortest distances and previous nodes for each node in the graph.


def main():
    # Given adjacency matrix
    adj_matrix1 = np.array(graph_data1, dtype=int)

    # Define the origin node (e.g., 0 for the first node)
    origin = 0

    # Run Dijkstra's algorithm
    dist, prev = dijkstra(adj_matrix1, origin)

    # Print the results
    print("Shortest distances:")
    for node, distance in enumerate(dist):
        print(f"Node {origin} to Node {node}: {distance}")

    # Print the array containing the previous node on the shortest path for each node
    print("Previous nodes on shortest path:")
    for node, prev_node in enumerate(prev):
        if prev_node is not None:
            print(f"Node {node}: {prev_node + 1}")
        if prev_node is  None:
            print(f"Node {node}: {0}")
            
if __name__ == "__main__":
    main()


Shortest distances:
Node 0 to Node 0: 0
Node 0 to Node 1: 8
Node 0 to Node 2: 25
Node 0 to Node 3: 17
Node 0 to Node 4: 36
Node 0 to Node 5: 37
Node 0 to Node 6: 26
Previous nodes on shortest path:
Node 0: 0
Node 1: 1
Node 2: 2
Node 3: 1
Node 4: 3
Node 5: 4
Node 6: 4


In [5]:
import numpy as np

def dijkstra(adj_matrix2, origin):
    num_nodes2 = len(adj_matrix2)
    dist = [float('inf')] * num_nodes2
    prev = [None] * num_nodes2
    dist[origin] = 0

    pq = PriorityQueue()
    pq.insert(origin, 0)

    while not pq.is_empty():
        u = pq.extract_min()
        for v in range(num_nodes2):
            if adj_matrix2[u][v] > 0:
                alt = dist[u] + adj_matrix2[u][v]
                if alt < dist[v]:
                    dist[v] = alt
                    prev[v] = u
                    if pq.contains(v):
                        pq.decrease_key(v, alt)
                    else:
                        pq.insert(v, alt)

    return dist, prev


def main():
    # Given adjacency matrix
    adj_matrix2 = np.array(graph_data2, dtype=int)

    # Define the origin node (e.g., 0 for the first node)
    origin = 0

    # Run Dijkstra's algorithm
    dist, prev = dijkstra(adj_matrix2, origin)

    # Print the results
    print("Shortest distances:")
    for node, distance in enumerate(dist):
        print(f"Node {origin} to Node {node}: {distance}")

    # Print the array containing the previous node on the shortest path for each node
    print("Previous nodes on shortest path:")
    for node, prev_node in enumerate(prev):
        if prev_node is not None:
            print(f"Node {node}: {prev_node + 1}")
        if prev_node is  None:
            print(f"Node {node}: {0}")# Adjust node numbering here

if __name__ == "__main__":
      main()

Shortest distances:
Node 0 to Node 0: 0
Node 0 to Node 1: 5
Node 0 to Node 2: 7
Node 0 to Node 3: inf
Node 0 to Node 4: inf
Node 0 to Node 5: inf
Previous nodes on shortest path:
Node 0: 0
Node 1: 1
Node 2: 2
Node 3: 0
Node 4: 0
Node 5: 0


In [6]:

def dijkstra(adj_matrix3, origin):
    num_nodes3 = len(adj_matrix3)
    dist = [float('inf')] * num_nodes3
    prev = [None] * num_nodes3
    dist[origin] = 0

    pq = PriorityQueue()
    pq.insert(origin, 0)

    while not pq.is_empty():
        u = pq.extract_min()
        for v in range(num_nodes3):
            if adj_matrix3[u][v] > 0:
                alt = dist[u] + adj_matrix3[u][v]
                if alt < dist[v]:
                    dist[v] = alt
                    prev[v] = u
                    if pq.contains(v):
                        pq.decrease_key(v, alt)
                    else:
                        pq.insert(v, alt)

    return dist, prev


def main():
    # Given adjacency matrix
    adj_matrix3 = np.array(graph_data3, dtype=int)

    # Define the origin node (e.g., 0 for the first node)
    origin = 0

    # Run Dijkstra's algorithm
    dist, prev = dijkstra(adj_matrix3, origin)

    # Print the results
    print("Shortest distances:")
    for node, distance in enumerate(dist):
        print(f"Node {origin} to Node {node}: {distance}")

    # Print the array containing the previous node on the shortest path for each node
    print("Previous nodes on shortest path:")
    for node, prev_node in enumerate(prev):
        if prev_node is not None:
            print(f"Node {node}: {prev_node + 1}")
        if prev_node is  None:
            print(f"Node {node}: {0}")# Adjust node numbering here

if __name__ == "__main__":
      main()

Shortest distances:
Node 0 to Node 0: 0
Node 0 to Node 1: 6
Node 0 to Node 2: 4
Node 0 to Node 3: 8
Previous nodes on shortest path:
Node 0: 0
Node 1: 3
Node 2: 1
Node 3: 2


In [7]:

def dijkstra(adj_matrix4, origin):
    num_nodes4 = len(adj_matrix4)
    dist = [float('inf')] * num_nodes4
    prev = [None] * num_nodes4
    dist[origin] = 0

    pq = PriorityQueue()
    pq.insert(origin, 0)

    while not pq.is_empty():
        u = pq.extract_min()
        for v in range(num_nodes4):
            if adj_matrix4[u][v] > 0:
                alt = dist[u] + adj_matrix4[u][v]
                if alt < dist[v]:
                    dist[v] = alt
                    prev[v] = u
                    if pq.contains(v):
                        pq.decrease_key(v, alt)
                    else:
                        pq.insert(v, alt)

    return dist, prev


def main():
    # Given adjacency matrix
    adj_matrix4 = np.array(graph_data4, dtype=int)

    # Define the origin node (e.g., 0 for the first node)
    origin = 0

    # Run Dijkstra's algorithm
    dist, prev = dijkstra(adj_matrix4, origin)

    # Print the results
    print("Shortest distances:")
    for node, distance in enumerate(dist):
        print(f"Node {origin} to Node {node}: {distance}")

    # Print the array containing the previous node on the shortest path for each node
    print("Previous nodes on shortest path:")
    for node, prev_node in enumerate(prev):
        if prev_node is not None:
            print(f"Node {node}: {prev_node + 1}")
        if prev_node is  None:
            print(f"Node {node}: {0}")# Adjust node numbering here

if __name__ == "__main__":
      main()

Shortest distances:
Node 0 to Node 0: 0
Node 0 to Node 1: 45
Node 0 to Node 2: 42
Node 0 to Node 3: 45
Node 0 to Node 4: 47
Previous nodes on shortest path:
Node 0: 0
Node 1: 3
Node 2: 1
Node 3: 1
Node 4: 1


In [8]:

def dijkstra(adj_matrix5, origin):
    num_nodes5 = len(adj_matrix5)
    dist = [float('inf')] * num_nodes5
    prev = [None] * num_nodes5
    dist[origin] = 0

    pq = PriorityQueue()
    pq.insert(origin, 0)

    while not pq.is_empty():
        u = pq.extract_min()
        for v in range(num_nodes5):
            if adj_matrix5[u][v] > 0:
                alt = dist[u] + adj_matrix5[u][v]
                if alt < dist[v]:
                    dist[v] = alt
                    prev[v] = u
                    if pq.contains(v):
                        pq.decrease_key(v, alt)
                    else:
                        pq.insert(v, alt)

    return dist, prev


def main():
    # Given adjacency matrix
    adj_matrix5 = np.array(graph_data5, dtype=int)

    # Define the origin node (e.g., 0 for the first node)
    origin = 0

    # Run Dijkstra's algorithm
    dist, prev = dijkstra(adj_matrix5, origin)

    # Print the results
    print("Shortest distances:")
    for node, distance in enumerate(dist):
        print(f"Node {origin} to Node {node}: {distance}")

    # Print the shortest path to a specific node (e.g., node 3)
    target_node = 3
    path = []
    while target_node is not None:
        path.insert(0, target_node)
        target_node = prev[target_node]
    print("Shortest path to Node 3:", path)

    # Print the array containing the previous node on the shortest path for each node
    print("Previous nodes on shortest path:")
    for node, prev_node in enumerate(prev):
        if prev_node is not None:
            print(f"Node {node}: {prev_node + 1}")
        if prev_node is  None:
            print(f"Node {node}: {0}")# Adjust node numbering here

if __name__ == "__main__":
      main()

Shortest distances:
Node 0 to Node 0: 0
Node 0 to Node 1: 425
Node 0 to Node 2: 403
Node 0 to Node 3: 48
Node 0 to Node 4: 274
Node 0 to Node 5: 202
Node 0 to Node 6: 12
Node 0 to Node 7: 51
Node 0 to Node 8: 141
Node 0 to Node 9: 270
Shortest path to Node 3: [0, 6, 3]
Previous nodes on shortest path:
Node 0: 0
Node 1: 3
Node 2: 9
Node 3: 7
Node 4: 7
Node 5: 8
Node 6: 1
Node 7: 1
Node 8: 7
Node 9: 8


In [9]:

def dijkstra(adj_matrix6, origin):
    num_nodes1 = len(adj_matrix6)
    dist = [float('inf')] * num_nodes6
    prev = [None] * num_nodes1
    dist[origin] = 0

    pq = PriorityQueue()
    pq.insert(origin, 0)

    while not pq.is_empty():
        u = pq.extract_min()
        for v in range(num_nodes6):
            if adj_matrix6[u][v] > 0:
                alt = dist[u] + adj_matrix6[u][v]
                if alt < dist[v]:
                    dist[v] = alt
                    prev[v] = u
                    if pq.contains(v):
                        pq.decrease_key(v, alt)
                    else:
                        pq.insert(v, alt)

    return dist, prev


def main():
    # Given adjacency matrix
    adj_matrix6 = np.array(graph_data6, dtype=int)

    # Define the origin node (e.g., 0 for the first node)
    origin = 0

    # Run Dijkstra's algorithm
    dist, prev = dijkstra(adj_matrix6, origin)

    # Print the results
    print("Shortest distances:")
    for node, distance in enumerate(dist):
        print(f"Node {origin} to Node {node}: {distance}")

    # Print the array containing the previous node on the shortest path for each node
    print("Previous nodes on shortest path:")
    for node, prev_node in enumerate(prev):
        if prev_node is not None:
            print(f"Node {node}: {prev_node + 1}")
        if prev_node is  None:
            print(f"Node {node}: {0}")# Adjust node numbering here

if __name__ == "__main__":
      main()

Shortest distances:
Node 0 to Node 0: 0
Node 0 to Node 1: 1260
Node 0 to Node 2: 390
Node 0 to Node 3: 1372
Node 0 to Node 4: 829
Node 0 to Node 5: 614
Node 0 to Node 6: 784
Node 0 to Node 7: 511
Node 0 to Node 8: 599
Node 0 to Node 9: 494
Node 0 to Node 10: 592
Node 0 to Node 11: 694
Node 0 to Node 12: 1108
Node 0 to Node 13: 605
Node 0 to Node 14: 642
Previous nodes on shortest path:
Node 0: 0
Node 1: 10
Node 2: 1
Node 3: 12
Node 4: 10
Node 5: 3
Node 6: 3
Node 7: 3
Node 8: 10
Node 9: 1
Node 10: 1
Node 11: 11
Node 12: 9
Node 13: 8
Node 14: 9
